const http=require('http'),fs=require('fs'),path=require('path'),https=require('https');
const PORT=process.env.PORT||3000;
// Load local .env without third-party dependencies. Never expose secrets to the browser.
try{for(const line of fs.readFileSync(path.join(__dirname,'.env'),'utf8').split(/\r?\n/)){const m=line.match(/^([A-Z0-9_]+)=(.*)$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2]}}catch{}
const ODDS_API_KEY=process.env.ODDS_API_KEY;
const ODDS_BOOKMAKER=process.env.ODDS_BOOKMAKER||'betmgm';
const Engine=require('./engine');
const Props=require('./props');
function getJSON(url,headers={}){return new Promise((resolve,reject)=>{https.get(url,{headers:{'User-Agent':'BeatTheBookie/0.2 (prototype)',Accept:'application/json',...headers}},r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>{try{const body=JSON.parse(d);if(r.statusCode>=400){const e=new Error(body.message||body.error||`HTTP ${r.statusCode}`);e.status=r.statusCode;return reject(e)}resolve({body,headers:r.headers})}catch(e){reject(e)}})}).on('error',reject)})}
const TEAM_STADIUM={
'Atlanta Falcons':[33.7554,-84.4008],'New Orleans Saints':[29.9511,-90.0812],'Dallas Cowboys':[32.7473,-97.0945],'Tampa Bay Buccaneers':[27.9759,-82.5033],
'Las Vegas Raiders':[36.0908,-115.1830],'Kansas City Chiefs':[39.0489,-94.4839],'Seattle Seahawks':[47.5952,-122.3316],'San Francisco 49ers':[37.4030,-121.9700],
'Carolina Panthers':[35.2258,-80.8528],'Detroit Lions':[42.3400,-83.0456]
};
async function weatherFor(team){const p=TEAM_STADIUM[team]; if(!p)return null; const meta=(await getJSON(`https://api.weather.gov/points/${p[0]},${p[1]}`)).body; const hourly=(await getJSON(meta.properties.forecastHourly)).body; return hourly.properties.periods?.[0]||null}
function implied(american){if(!american||typeof american!=='number')return null;return american<0?(-american)/((-american)+100):100/(american+100)}
function normalizeEvent(e){const c=e.competitions?.[0]||{}, teams=c.competitors||[]; const home=teams.find(x=>x.homeAway==='home'),away=teams.find(x=>x.homeAway==='away'); const odds=c.odds?.[0]||{}; return {id:e.id,name:e.name,date:e.date,status:e.status?.type?.description,home:home?.team?.displayName,away:away?.team?.displayName,homeScore:home?.score,awayScore:away?.score,venue:c.venue?.fullName,odds:{provider:odds.provider?.name||null,details:odds.details||null,overUnder:odds.overUnder||null,spread:odds.spread||null,homeML:odds.homeTeamOdds?.moneyLine||null,awayML:odds.awayTeamOdds?.moneyLine||null}}}
async function fetchOdds(){if(!ODDS_API_KEY)throw new Error('ODDS_API_KEY is not configured');const url=`https://api.the-odds-api.com/v4/sports/americanfootball_nfl/odds/?apiKey=${encodeURIComponent(ODDS_API_KEY)}&bookmakers=${encodeURIComponent(ODDS_BOOKMAKER)}&markets=h2h,spreads,totals&oddsFormat=american&dateFormat=iso`;const out=await getJSON(url);return {events:(out.body||[]).map(e=>({id:e.id,date:e.commence_time,home:e.home_team,away:e.away_team,bookmakers:(e.bookmakers||[]).map(b=>({key:b.key,title:b.title,lastUpdate:b.last_update,markets:b.markets}))})),headers:out.headers}}

async function fetchEvents(){if(!ODDS_API_KEY)throw new Error('ODDS_API_KEY is not configured');const out=await getJSON(`https://api.the-odds-api.com/v4/sports/americanfootball_nfl/events?apiKey=${encodeURIComponent(ODDS_API_KEY)}&dateFormat=iso`);return {events:out.body||[],headers:out.headers}}
async function fetchEventProps(eventId){if(!ODDS_API_KEY)throw new Error('ODDS_API_KEY is not configured');const markets=Props.PROP_MARKETS.join(',');const url=`https://api.the-odds-api.com/v4/sports/americanfootball_nfl/events/${encodeURIComponent(eventId)}/odds?apiKey=${encodeURIComponent(ODDS_API_KEY)}&bookmakers=${encodeURIComponent(ODDS_BOOKMAKER)}&markets=${encodeURIComponent(markets)}&oddsFormat=american&dateFormat=iso`;return getJSON(url)}

async function seasonRecords(){try{const data=(await getJSON('https://site.api.espn.com/apis/v2/sports/football/nfl/standings')).body;const rec={};for(const child of data.children||[])for(const entry of child.standings?.entries||[]){const stats=Object.fromEntries((entry.stats||[]).map(x=>[x.name,x.value]));rec[entry.team?.displayName]={games:stats.gamesPlayed||0,wins:stats.wins||0,losses:stats.losses||0,pointsFor:stats.pointsFor||0,pointsAgainst:stats.pointsAgainst||0}}return rec}catch{return {}}}
function summarizeInjuries(raw){const adj={};function walk(x,team){if(!x||typeof x!=='object')return;const next=x.displayName||x.team?.displayName||team;if(Array.isArray(x.injuries))for(const i of x.injuries){const st=(i.status||i.type?.description||'').toLowerCase();let w=st.includes('out')?1.2:st.includes('doubt')?.8:st.includes('question')?.35:0;adj[next]=(adj[next]||0)+w}for(const v of Object.values(x))if(typeof v==='object')walk(v,next)}walk(raw,null);return adj}
async function api(req,res){try{
 if(req.url.startsWith('/api/games')){const data=(await getJSON('https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard')).body; const games=(data.events||[]).map(normalizeEvent); return send(res,{updatedAt:new Date().toISOString(),source:'ESPN public endpoint (unofficial)',games});}
 if(req.url.startsWith('/api/injuries')){const data=(await getJSON('https://site.api.espn.com/apis/site/v2/sports/football/nfl/injuries')).body; return send(res,{updatedAt:new Date().toISOString(),source:'ESPN public endpoint (unofficial)',data});}
 if(req.url.startsWith('/api/odds')){
  if(!ODDS_API_KEY)return send(res,{error:'ODDS_API_KEY is not configured'},503);
  const url=`https://api.the-odds-api.com/v4/sports/americanfootball_nfl/odds/?apiKey=${encodeURIComponent(ODDS_API_KEY)}&bookmakers=${encodeURIComponent(ODDS_BOOKMAKER)}&markets=h2h,spreads,totals&oddsFormat=american&dateFormat=iso`;
  const out=await getJSON(url);
  const games=(out.body||[]).map(e=>({id:e.id,date:e.commence_time,home:e.home_team,away:e.away_team,bookmakers:(e.bookmakers||[]).map(b=>({key:b.key,title:b.title,lastUpdate:b.last_update,markets:b.markets}))}));
  return send(res,{updatedAt:new Date().toISOString(),source:'The Odds API',bookmaker:ODDS_BOOKMAKER,quota:{remaining:out.headers['x-requests-remaining']||null,used:out.headers['x-requests-used']||null,lastCost:out.headers['x-requests-last']||null},games});
 }
 if(req.url.startsWith('/api/props?')){const u=new URL(req.url,'http://x');let eventId=u.searchParams.get('eventId');if(!eventId)return send(res,{error:'eventId is required; get it from /api/prop-events'},400);const out=await fetchEventProps(eventId);const props=Props.rankMarket(Props.deVigProps(Props.normalizeEventProps(out.body,ODDS_BOOKMAKER)));return send(res,{updatedAt:new Date().toISOString(),source:'The Odds API',bookmaker:ODDS_BOOKMAKER,event:{id:out.body.id,home:out.body.home_team,away:out.body.away_team,date:out.body.commence_time},quota:{remaining:out.headers['x-requests-remaining']||null,used:out.headers['x-requests-used']||null,lastCost:out.headers['x-requests-last']||null},warning:'Player rows are market-only until a validated player projection is available. No model edge is fabricated.',props});}
 if(req.url.startsWith('/api/prop-events')){const out=await fetchEvents();return send(res,{updatedAt:new Date().toISOString(),source:'The Odds API',events:(out.events||[]).map(e=>({id:e.id,home:e.home_team,away:e.away_team,date:e.commence_time})),quota:{remaining:out.headers['x-requests-remaining']||null,used:out.headers['x-requests-used']||null,lastCost:out.headers['x-requests-last']||null}});}
 if(req.url.startsWith('/api/weather?')){const u=new URL(req.url,'http://x'); const team=u.searchParams.get('team'); const w=await weatherFor(team); return send(res,{updatedAt:new Date().toISOString(),source:'National Weather Service',team,weather:w});}
 if(req.url.startsWith('/api/analyze')){const [odds,records,injRaw]=await Promise.all([fetchOdds(),seasonRecords(),getJSON('https://site.api.espn.com/apis/site/v2/sports/football/nfl/injuries').then(x=>x.body).catch(()=>({}))]);const injuryAdj=summarizeInjuries(injRaw);const analyses=odds.events.map(g=>Engine.modelGame(g,records,injuryAdj,{}));const bestBets=Engine.rank(analyses,{minEdge:.025}).slice(0,20);const parlays={conservative:Engine.buildParlay(bestBets.filter(x=>x.confidence>=58),3),balanced:Engine.buildParlay(bestBets,4),aggressive:Engine.buildParlay(bestBets,6)};return send(res,{updatedAt:new Date().toISOString(),engineVersion:'0.3',bookmaker:ODDS_BOOKMAKER,methodology:'Baseline model using season scoring margin, record strength, home field, injury-status penalty, market de-vigging and uncertainty thresholds. Weather is exposed separately and can be applied as stadium forecasts are resolved.',warning:'Model probabilities are estimates, not guarantees. Positive edge can lose and small samples are noisy.',quota:{remaining:odds.headers['x-requests-remaining']||null,used:odds.headers['x-requests-used']||null,lastCost:odds.headers['x-requests-last']||null},bestBets,parlays,games:analyses});}
 send(res,{error:'Not found'},404)
}catch(e){send(res,{error:e.message},500)}}
function send(res,obj,status=200){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
const server=http.createServer((req,res)=>{if(req.url.startsWith('/api/'))return api(req,res);let p=req.url==='/'?'/index.html':req.url; p=path.join(__dirname,'public',p); if(!p.startsWith(path.join(__dirname,'public')))return res.end(); fs.readFile(p,(e,b)=>{if(e){res.writeHead(404);return res.end('Not found')} const ext=path.extname(p);res.writeHead(200,{'Content-Type':ext==='.html'?'text/html':ext==='.js'?'text/javascript':'text/css'});res.end(b)})});
server.listen(PORT,()=>console.log(`Beat the Bookie running on http://localhost:${PORT}`));
